# Generated by Django 2.2.28 on 2023-11-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Learner', 'Learner'), ('Leader', 'Leader'), ('Admin', 'Admin')], default='Leader', max_length=10),
        ),
    ]
